# Generated by Django 4.0.2 on 2022-03-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_comment_voice_alter_gift_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='gift',
            options={'verbose_name': 'Подарок', 'verbose_name_plural': 'Подарки'},
        ),
        migrations.AlterModelOptions(
            name='gifttype',
            options={'verbose_name': 'Тип подарка', 'verbose_name_plural': 'Типы подарков'},
        ),
        migrations.AlterModelOptions(
            name='hobby',
            options={'verbose_name': 'Интерес', 'verbose_name_plural': 'Интересы'},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'verbose_name': 'Праздник', 'verbose_name_plural': 'Праздники'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'Статус заказа', 'verbose_name_plural': 'Статусы заказов'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'Упаковка', 'verbose_name_plural': 'Упаковки'},
        ),
        migrations.AlterModelOptions(
            name='recipient',
            options={'verbose_name': 'Получатель', 'verbose_name_plural': 'Получатели'},
        ),
        migrations.AlterModelOptions(
            name='sex',
            options={'verbose_name': 'Пол', 'verbose_name_plural': 'Пола'},
        ),
    ]
