[tool.black]
line-length = 88
target-version = ["py38"]
skip-string-normalization = true

[tool.isort]
line_length = 88
combine_as_imports = true
order_by_type = true
length_sort_straight = true
include_trailing_comma = true
use_parentheses = true
multi_line_output = 3
known_local_folder = ['action', 'conf', 'crud', 'handlers', 'models', 'state', 'template', 'customer', 'django_gift']
