# Generated by Django 4.0.2 on 2022-03-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='Телеграм логин')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('chat_id', models.IntegerField(blank=True, null=True)),
                ('account_status', models.CharField(blank=True, default='customer', max_length=32, null=True, verbose_name='Роль')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipients', models.ManyToManyField(blank=True, default=[], related_name='customers', to='recipient.Recipient', verbose_name='Получатели')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'user',
            },
        ),
    ]
