# Generated by Django 4.0.2 on 2022-03-20 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('recipient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
        ),
        migrations.AddField(
            model_name='suggestedgift',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Отправитель'),
        ),
        migrations.AddField(
            model_name='suggestedgift',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipient.gift', verbose_name='Подарок'),
        ),
        migrations.AddField(
            model_name='suggestedgift',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipient.recipient', verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='gifts',
            field=models.ManyToManyField(related_name='recipients', through='recipient.SuggestedGift', to='recipient.Gift'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='hobbies',
            field=models.ManyToManyField(related_name='recipients', to='recipient.Hobby', verbose_name='Интересы'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='holidays',
            field=models.ManyToManyField(related_name='recipients', to='recipient.Holiday', verbose_name='Праздники'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipient.sex', verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Отправитель'),
        ),
        migrations.AddField(
            model_name='order',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipient.gift', verbose_name='Подарок'),
        ),
        migrations.AddField(
            model_name='order',
            name='holiday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipient.holiday', verbose_name='Праздник'),
        ),
        migrations.AddField(
            model_name='order',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recipient.package', verbose_name='Упаковка'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipient.recipient', verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipient.orderstatus', verbose_name='Статус заказа'),
        ),
        migrations.AddConstraint(
            model_name='hobby',
            constraint=models.UniqueConstraint(fields=('name',), name='unique hobby name'),
        ),
        migrations.AddField(
            model_name='gift',
            name='hobbies',
            field=models.ManyToManyField(related_name='gifts', to='recipient.Hobby', verbose_name='Интересы'),
        ),
        migrations.AddField(
            model_name='gift',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipient.package', verbose_name='Упаковка'),
        ),
        migrations.AddField(
            model_name='gift',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipient.sex', verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='gift',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipient.gifttype', verbose_name='Тип подарка'),
        ),
        migrations.AddField(
            model_name='comment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Отправитель'),
        ),
        migrations.AddField(
            model_name='comment',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipient.recipient', verbose_name='Получатель'),
        ),
        migrations.AddConstraint(
            model_name='suggestedgift',
            constraint=models.UniqueConstraint(fields=('customer_id', 'gift_id', 'recipient_id'), name='unique suggested gift'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('gift_id', 'recipient_id'), name='unique ordered gift'),
        ),
    ]
