# Generated by Django 4.0.2 on 2022-03-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='voice',
            field=models.FileField(null=True, upload_to='voice_cache/'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=models.ImageField(upload_to='img_cache/gifts', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(upload_to='img_cache/packages', verbose_name='package_img'),
        ),
    ]
