# Generated by Django 4.0.2 on 2022-03-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=models.ImageField(null=True, upload_to='img_cache/gifts', verbose_name='Картинка'),
        ),
    ]
