# Generated by Django 4.0.2 on 2022-03-20 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0003_alter_gift_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='hobbies',
            field=models.ManyToManyField(null=True, related_name='gifts', to='recipient.Hobby', verbose_name='Интересы'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipient.package', verbose_name='Упаковка'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='recipient.gifttype', verbose_name='Тип подарка'),
        ),
    ]
