# Generated by Django 4.0.2 on 2022-03-13 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0003_alter_comment_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=128, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.recipient', verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='voice',
            field=models.FileField(null=True, upload_to='voice_cache/', verbose_name='Аудио'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='account_status',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='recipients',
            field=models.ManyToManyField(blank=True, default=[], related_name='customers', to='customer.Recipient', verbose_name='Получатели'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='Телеграм логин'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='coolness',
            field=models.IntegerField(verbose_name='Прикольность'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='description',
            field=models.CharField(max_length=256, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='hobbies',
            field=models.ManyToManyField(related_name='gifts', to='customer.Hobby', verbose_name='Интересы'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=models.ImageField(upload_to='img_cache/gifts', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='link',
            field=models.CharField(max_length=256, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.package', verbose_name='Упаковка'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.sex', verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.gifttype', verbose_name='Тип подарка'),
        ),
        migrations.AlterField(
            model_name='gifttype',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активен?'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateField(blank=True, null=True, verbose_name='Отправлен в'),
        ),
        migrations.AlterField(
            model_name='order',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.gift', verbose_name='Подарок'),
        ),
        migrations.AlterField(
            model_name='order',
            name='holiday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.holiday', verbose_name='Праздник'),
        ),
        migrations.AlterField(
            model_name='order',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.package', verbose_name='Упаковка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.recipient', verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.orderstatus', verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(upload_to='img_cache/packages', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='birthday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='company_name',
            field=models.CharField(max_length=256, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='contact_info',
            field=models.CharField(max_length=256, verbose_name='Контактная информация'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='delivery_address',
            field=models.CharField(max_length=256, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='full_name',
            field=models.CharField(max_length=256, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='hobbies',
            field=models.ManyToManyField(related_name='recipients', to='customer.Hobby', verbose_name='Интересы'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='holidays',
            field=models.ManyToManyField(related_name='recipients', to='customer.Holiday', verbose_name='Праздники'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='position',
            field=models.CharField(max_length=256, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.sex', verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='sex',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='suggestedgift',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='suggestedgift',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.gift', verbose_name='Подарок'),
        ),
        migrations.AlterField(
            model_name='suggestedgift',
            name='presented',
            field=models.BooleanField(default=False, verbose_name='Подарен?'),
        ),
        migrations.AlterField(
            model_name='suggestedgift',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.recipient', verbose_name='Получатель'),
        ),
    ]
