# Generated by Django 4.0.2 on 2022-03-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0004_alter_comment_comment_alter_comment_customer_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hobby',
            constraint=models.UniqueConstraint(fields=('name',), name='unique hobby name'),
        ),
    ]
